feat : react query dev tools 추가

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,15 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run lint
+
+# if lint fails, don't commit
+if [ $? -ne 0 ]; then
+  echo "Lint failed, please fix the errors and try again."
+  exit 1
+fi
+
+# if lint fixes, commit
+if [ $? -eq 0 ]; then
+  echo "Lint passed, committing..."
+  exit 0
+fi
